version: "3.9"

services:
  redis:
    container_name: redis
    image: 'redis:6.2-alpine'
    ports:
      - "6379:6379"
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=frontgate
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
  frontgate:
    image: frontgate:latest
    ports:
      - "3000:3000"
    container_name: frontgate
    depends_on:
      - redis
      - postgres
    stdin_open: true
    volumes:
       - ./:/usr/src/app/my-app
      #  - /usr/src/app/my-app/node_modules
